### PR TITLE
generate command command

### PR DESCRIPTION
**Pull request by ddpkts**

### CODE REVIEW

**Comment by ddpkts** [comment]
sorry with no tests

**Comment by EllisV** [comment]
Hey @ddpkts,

Great to see you contributing to OXID console, but I'm currently working on having 1.3 version of OXID Console which will be shipped as composer package. I do not want to introduce new stuff for 1.2 version unless it is necessary.

Regards having this command on 1.3 I would also not rush to contribute as I am thinking of redefining Command interface if I will successfully be able to support both old and new definition of interface. You can check the progress on 1.3 branch (:

**Comment by ddpkts** [comment]
okay no worries, let's wait for the 1.3

**Comment by EllisV** [comment]
Alright, are you ok if I close this pull request for now?

**Comment by ddpkts** [comment]
sure, np

**Pull request closed without merging**
